#! /usr/bin/python3

from optparse import OptionParser
import os
import sys

class unBuffered(object):
    def __init__(self, stream):
        self.stream = stream
    
    def write(self, data):
        self.stream.write(data)
        self.stream.flush()

    def writelines(self, datas):
        self.stream.writelines(datas)
        self.stream.flush() 
    
    def __getattr__(self, attr):
        return getattr(self.stream, attr)
    
sys.stdout = unBuffered(sys.stdout) # redid the sys.stdout class
sys.stderr = unBuffered(sys.stderr) # redid the sys.stderr class

sys.stderr.write("#This is Standard Error\n")
print("Hello World")
sys.stdout.write("#This is Standard Output and Not an Error\n")
# sys.stdout.flush()

parser = OptionParser()
parser.add_option("-f", "--file", dest="filename", help="Input file", metavar="FILE")
(options, args) = parser.parse_args()

if(not options.ensure_value("filename", "")):
    filename = input ("Enter the file name: ")
    os.system(f"cat {filename}")

os.system("cat "+options.ensure_value("filename", "main"))