#! /usr/bin/python3

import multiprocessing
import os


def downloadFile(url, output):
    # os.system("wget -o {output} {url}".format(url=url, output=output)) # proper way but I can't understand.....
    os.system(f"wget -o {output} {url}")


if __name__ == "__main__":
    try:
        while True:
            # Creating the new thread........
            multiprocessing.Process(target=downloadFile, args=(input('Enter url: '), input('Enter Output File name: '))).start()
    except KeyboardInterrupt as e:
        print("Quitting....")
